[project]
name = "pydantic-ai-101"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nest-asyncio>=1.6.0",
    "pydantic>=2.12.5",
    "pydantic-ai>=1.52.0",
    "pydantic-settings>=2.12.0",
]
